### ISSUE TITLE
[BUG] Json data from request on attempt to connect is empty

### ISSUE THREAD

**Issue by josValentin** [frankvHoof93/TikTokLiveSharp#103]
Until yesterday the responses from the api were ok, but today when trying to connect to any tiktok account, the response from request is empty, this causes a json error parsing, any idea about what's happening?

**Comment by steampoweredtaco** [comment]
Removing this line should fix the issue, but I don't have the setup to test. 
https://github.com/frankvHoof93/TikTokLiveSharp/blob/be7cb0ef6728d0a9bd716aa32cf5a8f326a0a635/TikTokLiveSharp/Client/Config/Constants.cs#L95

The issue is that TikTok deprecated the version specifier at that level.  I imagine you can add a higher version but I don't know what ATM.

**Comment by josValentin** [comment]
Thanks for the reply!, sadly it didn't worked :( I am aware about any other possible fix.

**Comment by steampoweredtaco** [comment]
Thanks, I was able to get up an environment and also confirmed this doesn't fix the issue.  I'm digging further.

**Comment by steampoweredtaco** [comment]
@josValentin I have a fix that works.
Remove the line like before:
https://github.com/frankvHoof93/TikTokLiveSharp/blob/be7cb0ef6728d0a9bd716aa32cf5a8f326a0a635/TikTokLiveSharp/Client/Config/Constants.cs#L95

But also change this line:
https://github.com/frankvHoof93/TikTokLiveSharp/blob/be7cb0ef6728d0a9bd716aa32cf5a8f326a0a635/TikTokLiveSharp/Client/Config/Constants.cs#L26

to:

`        public const string USER_AGENT = "Mozilla 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36";`

**Comment by josValentin** [comment]
It did the trick! I really appreciate your help :) thanks!!!
