### ISSUE TITLE
One or more errors occurred. (LiveStream for HostID could not be found. Is the Host online?)

### ISSUE THREAD

**Issue by huudatk53** [frankvHoof93/TikTokLiveSharp#57]
I also check user live stream on tiktok right then, but I run, throw error One or more errors occurred. (LiveStream for HostID could not be found. Is the Host online?)

**Comment by Daviko291** [comment]
I have the same error

**Comment by minhiclick** [comment]
me too

**Comment by Yoshisan0** [comment]
me too

**Comment by frankvHoof93** [comment]
18+-rooms and 'protected'/'privated' rooms will often not be able to connect by ID.
This is because the library attempts to scrape the HTML for the page for the RoomID.
For these specific rooms, the page requires logging in in order to get this info.

If you can, try to grab the RoomID from the HTML yourself (search for 'room_id=').
You can use that to connect with instead.
